name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # NOTE: UTCなので9時間引く
    # 毎週土曜日の22時に実行
    - cron: 0 11 * * 6
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-22.04  # ubuntu-20.04 → ubuntu-22.04 に変更
    timeout-minutes: 10

    steps:
      - name: Git checkout
        uses: actions/checkout@v4  # v2 → v4 に更新

      - name: Setup node
        uses: actions/setup-node@v4  # v2 → v4 に更新
        with:
          node-version: 18.20.0  # 14.20.0 → 18.20.0 に更新 (LTSバージョン)
          cache: yarn

      - name: Install node packages
        run: yarn install

      - name: Run lint
        run: yarn lint

      - name: Run type check
        run: yarn type-check

      - name: Run test
        run: yarn test 
